### ISSUE TITLE
프로젝트에 useReactHook 라이브러리 import 시 useImagePreSetup가 발생하는 문제

### ISSUE THREAD

**Issue by suhyeoonn** [frontend-opensource-project/use-react-hooks#120]
useDebounce 훅을 사용하기 위해 라이브러리를 가져왔는데, useImagePreSetup에서 문제가 발생했습니다.
<img width="764" alt="image" src="https://github.com/user-attachments/assets/e17ff8bc-1e7c-4ab3-89d1-2e7854eaca44">

node_modules 폴더를 확인해보니, #107 에서 삭제된 파일이 아직 그대로 남아있더라고요! 캐시 문제 같아요.
<img width="323" alt="image" src="https://github.com/user-attachments/assets/e9ece128-b2e4-48bf-8c9b-8a922c625a15">

지피티에게 물어보니 아래처럼 해결할 수 있다고 하네요! 참고 부탁드립니다
### 패키지의 캐시 문제
빌드 캐시 또는 타입스크립트 트랜스파일러(TSC)의 캐시 문제로 인해 최신 변경사항이 반영되지 않을 수 있습니다.

해결 방법:
1. 캐시 제거
```bash
rm -rf node_modules .next dist
npm install
npm run build
```
2. 타입스크립트 캐시 재생성
```bash
npx tsc --build --clean
npx tsc
```

**Comment by bicochan** [comment]
- commit: 27af07750853f897e034fea428b92a4cdc163f67

v1.1.3에 새롭게 번들링한 구조 반영되었습니다!

![www npmjs com_package_@frontend-opensource_use-react-hooks_activeTab=code](https://github.com/user-attachments/assets/a3356bda-01d7-4ebf-acc4-fc6b3232ac4f)
